project_id = "wnsubdtajsawsotcpozh"

[functions.translate]
verify_jwt = false

[functions.dictionary]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.scrape-url]
verify_jwt = false

[functions.verify-quiz]
verify_jwt = false

[functions.generate-learning-questions]
verify_jwt = false

[functions.get-learning-questions]
verify_jwt = false

[functions.replenish-question-queue]
verify_jwt = false

[functions.image-translate]
verify_jwt = false
